version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports: 
      - "3000:3000"
    volumes: 
      - ./conf:/usr/share/grafana/conf
    environment: 
      - GF_INSTALL_PLUGINS=marcusolsson-dynamictext-panel,grafana-simple-json-datasource,grafana-piechart-panel,frser-sqlite-datasource,grafana-image-renderer
    restart: always
  db:
    image: postgres:10
    #ports:
    #  - "5442:5432"
    environment:
      - POSTGRES_DB=${GRAFANA_DB_NAME}
      - POSTGRES_PASSWORD=${GRAFANA_DB_PASSWORD}
      - POSTGRES_USER=${GRAFANA_DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - grafana-db-data:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  grafana-db-data: