version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports: 
      - "3000:3000"
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_PASSWORD=grafana
      - POSTGRES_USER=grafana
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: