version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports: 
      - "3000:3000"
    volumes: 
      - ./conf:/usr/share/grafana/conf
  db:
    image: postgres:10
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_PASSWORD=grafana
      - POSTGRES_USER=grafana
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - grafana-db-data:/var/lib/postgresql/data/pgdata
volumes:
  grafana-db-data: